board/urls.py
#from django.urls import path
from django.conf.urls import url
from .views import (PostListView,
					PostDetailView,
					PostCreateView,
					PostUpdateView,
					PostDeleteView,
					PostTestView
                   )

app_name = 'board'

urlpatterns = [
		url(r'^$', PostListView.as_view(), name='notice-board'),
		url(r'^posts/(?P<pk>\d+)/$', PostDetailView.as_view(), name='post-detail'),
		url(r'^posts/new', PostCreateView.as_view(), name='post-create'),
		url(r'^posts/(?P<pk>\d+)/edit/', PostUpdateView.as_view(), name='post-update'),
		url(r'^posts/(?P<pk>\d+)/delete/', PostDeleteView.as_view(), name='post-delete'),
		url(r'^posts/js', PostTestView.as_view(), name='post-test'),
]

test_board/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^notice-board/', include('board.urls')),
]

# file upload works fine without the line below, it seems like 1.11 doesn't need this bits
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# from django.contrib import admin
# from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static
#
# urlpatterns = [
#                   path('admin/', admin.site.urls),
#                   path('notice-board/', include('board.urls'))
#               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    post_date = models.DateField(auto_now_add=True)
    post_edited = models.DateTimeField(auto_now=True)
    post_created = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='upload_files/', max_length=100, null=True, blank=True, default=None)

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('board:post-detail', kwargs={'pk': self.pk})
        #return reverse('board:notice-board')

    class Meta:
        ordering = ('post_created',)

board/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import reverse_lazy
from django.views.generic import (ListView, DetailView, CreateView, UpdateView, DeleteView)
from .models import Post
from .filters import PostFilter
#from .forms import PostForm, EditForm

from django.contrib import messages
from django.db.models import Q

class PostListView(ListView):
    model = Post
    #template_name = 'board/post_list.html'
    template_name = 'board/post_list_filter.html'
    ordering = ['-post_created']
    paginate_by = 5
    context_object_name = 'object_list'

    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        object_list = Post.objects.order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_object_list = object_list.filter(
                        Q(title__icontains=search_keyword) | Q(body__icontains=search_keyword)
                        | Q(author__username__icontains=search_keyword))
                elif search_type == 'title_body':
                    search_object_list = object_list.filter(
                        Q(title__icontains=search_keyword) | Q(body__icontains=search_keyword))
                elif search_type == 'title':
                    search_object_list = object_list.filter(title__icontains=search_keyword)
                elif search_type == 'body':
                    search_object_list = object_list.filter(body__icontains=search_keyword)
                elif search_type == 'author__username':
                    search_object_list = object_list.filter(author__username__icontains=search_keyword)
                return search_object_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return object_list

    def get_context_data(self, **kwargs):
        #pagination
        context = super(PostListView, self).get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index
        page_range = paginator.page_range #[start_index:end_index]
        context['page_range'] = page_range

        #filter
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        notice_fixed = Post.objects.all().order_by('-id')

        if len(search_keyword) > 1:
            context['q'] = search_keyword
        context['type'] = search_type
        context['notice_fixed'] = notice_fixed

        return context

# title, body 각각 검색
    # def get_queryset(self):
    #     queryset = super(PostListView, self).get_queryset()
    #     filter = PostFilter(self.request.GET, queryset)
    #     return filter.qs


class PostDetailView(DetailView):
    model = Post
    template_name = 'board/post_detail.html'
    context_object_name = 'post'


class PostCreateView(CreateView):
    model = Post
    template_name = 'board/post_form.html'

    #template_name = 'board/post_form_feedback.html'
    #templatfor updated JS: currently not working

    fields = '__all__'
    #form_class = PostForm #returns 'FileField' object has no attribute 'use_required_attribute' error


class PostTestView(CreateView):
    model = Post
    template_name = 'board/form_js_test.html'
    fields = '__all__'


class PostUpdateView(UpdateView):
    model = Post
    fields = '__all__'
    template_name = 'board/post_form_django.html'

    #template_name = 'board/post_form.html'
    # 'post_form' returns nothing.
    # The reason why 'form.html' in 'post_form_django.html' works is because 'html element in 'post_form' is copied from developers tool


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'board/post_confirm_delete.html'
    success_url = reverse_lazy('board:notice-board')

board/templates/board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Notice Board</title>
    <meta charset="UTF-8">
</head>
<body>
   <div id="warp">
        <div id="header">
        </div>
        <div id="content">
            <h1>  <a href="{% url 'board:notice-board' %}"> Notice Board </a></h1>
            <div class="container">
                {% block content %}
                {% endblock content %}
                <br><br>
            </div>
        </div>
    </div>
</body>
</html>

board/templates/board/post_confirm_delete.html
{% extends './base.html' %}

{% block content %}
<div class="confirm">
    <p class="title">Post: [{{post.title}}]</p>
    <p>Are you sure you want to delete this post?</p>
    <form method="POST">{% csrf_token %}
        <div class="confirm_btn">
            <input type="submit" value="Delete">
        </div>
    </form>
</div>
{% endblock content %}

board/templates/board/post_detail.html
{% extends './base.html' %}


    <div class="container">
        <h1 class="title">{{post.title}}</h1>
        <p class="date">{{post.date_created}}</p>
    </div>


{% block content %}
    <div class="content">
        <div class="container">
        <h2 class="title">{{post.title}}</h2>
        <p class="date">{{post.author}}</p>
        <p class="date">{{post.post_date}}</p>
        <hr>

        <p class="text">{{post.body|linebreaksbr}}</p>

        {% if post.file %}
               <p class="file"> File: {{post.file}}</p>
              {% else %}
            <p> File: N/A </p>
              {% endif %}
        <hr>

        </div>
    </div>
    <div class="btn">
        <div class="btn_list"><a href="{% url 'board:notice-board' %}">Back to list</a></div>
        <div class="right-btn">
            <div class="btn_modify"><a href="{% url 'board:post-update' post.id %}">Edit</a></div>
            <div class="btn_delete"><a href="{% url 'board:post-delete' post.id %}">Delete</a></div>
        </div>
    </div>
{% endblock content %}

board/templates/board/post_form.html
{% extends './base.html' %}

{% block content %}
{% if user.is_authenticated %}

<div class="container">
    <h2> POST for test branch 2 merge conflict </h2>
        <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
            <div class="editor">
                 <br>
<!--{# FORM FIELDS  #}-->
                <label for="title">title</label> <input type="text" name="title" maxlength="100" placeholder="Enter title" id="id_title">
                 <p>{{form.author}}</p>
                <label for="body"></label><textarea name="body" cols="40" rows="10" id="id_body" placeholder="Enter content"></textarea>
                <div class="file-upload">
                    <label for="file"></label><input type="file" name="file" id="id_file">
                </div>
                <br><br>
            </div>
<!--{# SUBMIT BUTTON#}-->
            <div class="submit">
                <input type="reset" value="reset">
                <input type="submit" name="submit"  value="submit">
            </div>
        </form>
    <div class="btn_back">
        <br><br>
        <a href="/notice-board/">Return to post list</a>
    </div>
</div>

{% else %}
<h1>You are not allowed to post, Please login</h1>
{% endif%}


<!--{# JAVA SCRIPT #}-->
    <script type="text/javascript">
    window.addEventListener("load", function(){
        let form = document.querySelector("form");
            form.addEventListener("submit", function(event) {
                let title = document.querySelector("input[name=title]");
                let body = document.querySelector("textarea[name=body]");

                    if(title.value === ""){
                        alert("타이틀 입력");
                        title.focus();
                        return false;
                    }

                    else if(body.value === ""){
                        alert("내용 입력");
                        title.focus();
                        return false;
                    }
            });
    });


    let name = "{{ user.id }}";
    document.getElementById("id_author").value = name;
    document.getElementById("id_author").style.visibility= "hidden";


    </script>

{% endblock content %}

board/templates/board/post_form_django.html
{% extends './base.html' %}

    <div class="container">
        <h1>글쓰기</h1>
    </div>

{% block content %}
    <h1> Post </h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="editor">
                <p>{{form.title}}</p>
                {% for error in form.title.errors %}
                    <p class="error">{{error}}</p>
                {% endfor %}
                <p>{{form.author}}</p>
                <p>{{form.body}}</p>
                {% for error in form.body.errors %}
                    <p class="error">{{error}}</p>
                {% endfor %}
                <p>{{form.file}}</p>
            </div>
            <div class="submit">
                <input type="submit" value="post">
            </div>
        </form>
    <div class="btn_back">
        <a href="{% url 'board:notice-board' %}" >Return to post list</a>
    </div>


<script type="text/javascript">
    let name = "{{ user.id }}";
    document.getElementById("id_author").value = name;
    document.getElementById("id_author").style.visibility= "hidden";
</script>



{% endblock content %}

board/templates/board/post_list.html
{% load pagination_extras %}
{% block title %}notice board{% endblock %}

{% block body %}
    <!-- post list -->
    <div class="btn_post">
        <h3><a href="{% url 'board:notice-board' %}"> Post List for test</a> | <a href="{% url 'board:post-create'%}"> Post </a> </h3>
        <hr>
    </div>

    {% if object_list.exists %}
    <table class="table">
            <tr>
              <th>#</th>
              <th>POST ID</th>
              <th>title</th>
              <th>file</th>
              <th>author</th>
              <th>date</th>
            </tr>
        <tbody>
            <tr>
        {% for post in object_list %}
              <td> {% pagination_reverse_numbering paginator page_obj forloop.counter0 %} </td>
              <td> {{ post.id }} </td>
              <td style="text-align:left"><a href="{% url 'board:post-detail' post.id %}">
                    {{ post.title|truncatechars:80 }}</a></td>
              {% if post.file %}
                <td> Y </td>
              {% else %}
                <td> N/A </td>
              {% endif %}
              <td>{{ post.author.username }}</td>
              <td>{{ post.post_date|date:'Y-m-d'}}</td>
            </tr>
        </tbody>
        {% endfor %}

    {% else %}
        No post yet.
    {% endif %}

    </table>

<!--PAGINATION start -->
<div class="row justify-content-md-center ">
    <div class="col-md-8">
      {% if is_paginated %}
<!-- Previous -->
          {% if page_obj.has_previous %}
             <a class="btn-sm mb-4 page-btn" href="?page=1">First</a>
             <a class="btn-sm mb-4 page-btn" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
          {% endif%}
<!-- List -->
          {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
                  <a class="btn-sm page-active mb-4" href="?page={{ num }}">{{ num }}</a>
              {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'5' %}
                  <a class="btn-sm mb-4 page-btn" href="?page={{ num }}">{{ num }}</a>
              {% endif %}
          {% endfor %}
<!--   Next       -->
          {% if page_obj.has_next %}
             <a class="btn-sm mb-4 page-btn" href="?page={{ page_obj.next_page_number}}">&raquo;</a>
             <a class="btn-sm mb-4 page-btn" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          {% endif%}
      {% endif %}
    </div>
</div>
<!--PAGENATION end-->

<!-- FILTER -->
    <form method="get" class="form-style">
        <div class="search-bar">

            <label for="id_title__icontains"> search </label>
            <input type="text" name="title__icontains" class="form-control is-valid form-style" placeholder="enter text" title="" id="id_title__icontains">

            <label for="id_body__icontains">by content</label>
            <input type="text" name="body__icontains" class="form-control is-valid" placeholder="enter text" title="" id="id_body__icontains">

            <input class="btn btn-primary" type="submit" name="btnsubmit" value="search">
            <input type="reset" value="reset" style="padding: 4px;">


        </div>
            <br>
    </form>

<style>
    table {
        width: 100%;
        text-align: center;

        border-collapse: collapse;
      }
    th, td {
        padding: 10px;

      }

</style>

{% endblock body %}

board/templates/board/post_list_filter.html
{% load pagination_extras %}
{% block title %}notice board{% endblock %}

 <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

{% block body %}
    <!-- post list -->
    <div class="btn_post">
        <h3><a href="{% url 'board:notice-board' %}"> Post List </a> | <a href="{% url 'board:post-create'%}"> Post </a> </h3>
        {% if q %}
            <h5><i class="fas fa-search"></i>&nbsp;'{{ q }}' 검색 결과입니다.</h5>
        {% else %}
            <h5><i class="fas fa-check"></i> 공지사항 리스트입니다.</h5>
        {% endif %}
        <hr>
    </div>

    <table class="table">
        <thead>
            <tr>
              <th>#</th>
              <th>POST ID</th>
              <th>title</th>
              <th>file</th>
              <th>author</th>
              <th>date</th>
            </tr>
        </thead>

        <tbody>
        {% if object_list %}
        {% for post in object_list %}
         <tr>
              <td> {% pagination_reverse_numbering paginator page_obj forloop.counter0 %} </td>
              <td> {{ post.id }} </td>
              <td style="text-align:left"><a href="{% url 'board:post-detail' post.id %}">
                    {{ post.title|truncatechars:80 }}</a></td>
              {% if post.file %}
                <td> Y </td>
              {% else %}
                <td> N/A </td>
              {% endif %}
              <td>{{ post.author }}</td>
              <td>{{ post.post_date|date:'Y-m-d'}}</td>
         </tr>
         {% endfor %}
         {% else %}

         {% if q %}
         <tr class="text-center">
             <td>
                 <i class="fas fa-info-circle"></i>&nbsp;일치하는 검색 결과가 없습니다.
             </td>
         </tr>
         {% else %}
             <tr class="text-center">
                 <td>
                     <i class="fas fa-info-circle"></i>&nbsp;작성된 게시글이 없습니다.
                 </td>
             </tr>
         {% endif %}
         {% endif %}
        </tbody>
    </table>
<!--LIST TABLE end-->

<!--FILTER start-->
        <form action="" method="GET">
            <div class="col">
                <div style="float: right;" class="form-row">
                    <div class="form-row">
                        <div class="col" style="margin-top: 10px;">
                            <select style="width: 6em;" class="custom-select custom-select-md" name="type">
                                <option value="all">전체</option>
                                <option value="title_body">제목+내용</option>
                                <option value="title">제목</option>
                                <option value="body">내용</option>
                                <option value="author__username">작성자</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col">
                            <button class="btn btn-sm" type="submit" id="search_btn">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
<!--FILTER end-->

<!--PAGINATION start-->
{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                tabindex="-1">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">이전</a>
        </li>
        {% endif %}

        {% for page in page_range %}
        <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
            <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
                href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
{% endif %}
<!--PAGINATION end -->


<style>
    table {
        width: 100%;
        text-align: center;

        border-collapse: collapse;
      }
    th, td {
        padding: 10px;
        font-weight: bold;
        color:gray;
      }
    h5 {
        color: gray;
        font-weight: 550;
        }
</style>

<script type="text/javascript">
    target = window.location.search.split('&')[0].split('=')[1]
    var type = document.getElementsByTagName('option')
    for (var i = 0; i < 5; i++) {
        if (type[i].value === target) {
            type[i].setAttribute('selected', 'selected')
        }
    }
</script>

{% endblock body %}

board/templates/board/post_list_pagination.html
{% load pagination_extras %}
{% block title %}notice board{% endblock %}

{% block body %}
    <!-- post list -->
    <div class="btn_post">
        <h1>Pagination Test</h1>
        <h3><a href="{% url 'board:notice-board' %}"> Post List </a> | <a href="{% url 'board:post-create'%}"> Post </a> </h3>
        <hr>
    </div>

    {% if object_list.exists %}
    <table class="table">
            <tr>
              <th>#</th>
              <th>POST ID</th>
              <th>title</th>
              <th>file</th>
              <th>author</th>
              <th>date</th>
            </tr>
        <tbody>
            <tr>
        {% for post in object_list %}
              <td> {% pagination_reverse_numbering paginator page_obj forloop.counter0 %} </td>
              <td> {{ post.id }} </td>
              <td style="text-align:left"><a href="{% url 'board:post-detail' post.id %}">
                    {{ post.title|truncatechars:80 }}</a></td>
              {% if post.file %}
                <td> Y </td>
              {% else %}
                <td> N/A </td>
              {% endif %}
              <td>{{ post.author.username }}</td>
              <td>{{ post.post_date|date:'Y-m-d'}}</td>
            </tr>
        </tbody>
        {% endfor %}

    {% else %}
        No post yet.
    {% endif %}

    </table>
<!--1111111111111111111111111 1 Pagination 1111111111111 1111111111111 -->
<!--        <div class="paginator">-->
<!--        <hr>-->
<!--            {% if page_obj.has_previous %}-->
<!--                <a href="?page=1" class="first">first</a>-->
<!--                <a href="?page={{page_obj.previous_page_number}}" class="prev">prev</a>-->
<!--            {% endif %}-->

<!--            <span class="page">-->
<!--                <p>{{page_obj.number}} of {{page_obj.paginator.num_pages}}</p>-->
<!--            </span>-->

<!--            {% if page_obj.has_next %}-->
<!--                <a href="?page={{page_obj.next_page_number}}" class="next">next</a>-->
<!--                <a href="?page={{page_obj.paginator.num_pages}}" class="last">last</a>-->
<!--            {% endif %}-->
<!--        </div>-->
<!--        <br>-->

<!--    {% else %}-->
<!--        <div class="blank">-->
<!--            <p>No post yet.</p>-->
<!--        </div>-->
<!--    {% endif %}-->

<!-- 222222222222222 pagination 2222222222222222222222222222222-->

<!--{% if is_paginated %}-->
<!--<ul class="pagination">-->
<!--    {% if page_obj.has_previous %}-->
<!--    <li class="page-item">-->
<!--        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"-->
<!--            tabindex="-1">이전</a>-->
<!--    </li>-->
<!--    {% else %}-->
<!--    <li class="page-item disabled">-->
<!--        <a class="page-link" href="#" tabindex="-1">이전</a>-->
<!--    </li>-->
<!--    {% endif %}-->

<!--    {% for page in page_range %}-->
<!--    <li class="page-item {% if page == page_obj.number %} activate {% endif %}">-->
<!--        <a class="page-link" href="?page={{ page }}">{{ page }}</a>-->
<!--    </li>-->
<!--    {% endfor %}-->

<!--    {% if page_obj.has_next %}-->
<!--    <li class="page-item">-->
<!--        <a class="page-link"-->
<!--            href="?page={{ page_obj.next_page_number }}">다음</a>-->
<!--    </li>-->
<!--    {% else %}-->
<!--    <li class="page-item disabled">-->
<!--        <a class="page-link" href="#">다음</a>-->
<!--    </li>-->
<!--    {% endif %}-->
<!--</ul>-->
<!--{% endif %}-->

<!-- 3333333333333333333333333 pagination 333333333333333333333333333333-->
<!--PAGINATION start -->
<div class="row justify-content-md-center ">
    <div class="col-md-8">
      {% if is_paginated %}
<!-- Previous -->
          {% if page_obj.has_previous %}
             <a class="btn-sm mb-4 page-btn" href="?page=1">First</a>
             <a class="btn-sm mb-4 page-btn" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
          {% endif%}
<!-- List -->
          {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
                  <a class="btn-sm page-active mb-4" href="?page={{ num }}">{{ num }}</a>
              {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'5' %}
                  <a class="btn-sm mb-4 page-btn" href="?page={{ num }}">{{ num }}</a>
              {% endif %}
          {% endfor %}
<!--   Next       -->
          {% if page_obj.has_next %}
             <a class="btn-sm mb-4 page-btn" href="?page={{ page_obj.next_page_number}}">&raquo;</a>
             <a class="btn-sm mb-4 page-btn" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          {% endif%}
      {% endif %}
    </div>
</div>
<!--PAGINATION end -->



<!-- FILTER -->

    <form method="get" class="form-style">
        <div class="search-bar">

            <label for="id_title__icontains"> search </label>
            <input type="text" name="title__icontains" class="form-control is-valid form-style" placeholder="enter text" title="" id="id_title__icontains">

            <label for="id_body__icontains">by content</label>
            <input type="text" name="body__icontains" class="form-control is-valid" placeholder="enter text" title="" id="id_body__icontains">

            <input class="btn btn-primary" type="submit" name="btnsubmit" value="search">
            <input type="reset" value="reset" style="padding: 4px;">


        </div>
            <br>
    </form>

<style>
    table {
        width: 100%;
        text-align: center;

        border-collapse: collapse;
      }
    th, td {
        padding: 10px;

      }

</style>

{% endblock body %}

board/templates/notice_board/post_form.html
{% extends './base.html' %}

{% block content %}
<div class="container">
    <h2> POST </h2>
        <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
            <div class="editor">
                 <br>
<!--{# FORM FIELDS  #}-->
                <label for="title">title</label> <input type="text" name="title" maxlength="100" placeholder="Enter title" id="id_title">
                 <p> author: {{form.author}}</p>
                <label for="body"></label><textarea name="body" cols="40" rows="10" id="id_body" placeholder="Enter content"></textarea>
                <div class="file-upload">
                    <label for="file"></label><input type="file" name="file" id="id_file">
                </div>
                <br><br>
            </div>
<!--{# SUBMIT BUTTON#}-->
            <div class="submit">
                <input type="reset" value="reset">
                <input type="submit" name="submit"  value="submit" onclick="return validate()"/>
            </div>
        </form>
    <div class="btn_back">
        <br><br>
        <a href="/notice-board/">Return to post list</a>
    </div>
</div>


<!--{# JAVA SCRIPT #}-->
    <script type="text/javascript">
    window.addEventListener("load", function(){
        let form = document.querySelector("form");
            form.addEventListener("submit", function(event) {
                let title = document.querySelector("input[name=title]");
                let body = document.querySelector("textarea[name=body]");

                    if(title.value === ""){
                        alert("타이틀 입력");
                        title.focus();
                        return false;
                    }

                    else if(body.value === ""){
                        alert("내용 입력");
                        title.focus();
                        return false;
                    }


            });
    });


    let name = "{{ user.id }}";
    document.getElementById("id_author").value = name;

    </script>

{% endblock content %}